name: multibox
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.2
  weather_icons: ^2.0.1
  geolocator: ^5.3.0
  http: ^0.12.0+4
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  dio: ^3.0.3
  flutter_bloc: ^0.21.0
  json_serializable: ^3.2.3
  intl: ^0.16.0
  url_launcher: ^5.2.0
  cached_network_image: ^2.0.0-rc
  flutter_stetho: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
